export const SEARCH_ARTICLE = 'SEARCH/GET_RESULT_SEARCH'
export const GET_INPUT_SEARCH = 'SEARCH/GET_INPUT_SEARCH'

export const GET_SEARCH_WEATHER = 'WEATHER/GET_INPUT_SEARCH'
export const GET_FORECAST = 'WEATHER/GET_RESULT_FORECAST'